### ISSUE TITLE
针对Mr.Trans.pdl 文件内容的提问

### ISSUE THREAD

**Issue by ahuai** [Illumine-Labs/Mr.Translate#2]
请问下大佬

```
Trans{
    meta {
        name: "Mr.Trans", author: "AlexZhang", version: "0.3"
    }

    commands_prefix: "/",
    import@Features.trans.commands,
    import@Features.trans.user_preferences,
    import@Features.trans.format,
    import@Features.trans.Dictionary,
    import@Features.trans.rules,

    ```
    Use GPT Plugins
    ```
    import@Features.trans.gpt-plugins-mode
}
```
这段代码 可以理解成是对"AI Language Translater"的身份限定不？ meta是它的一些基础信息，import@Features.trans.xxx 是各自自定义插件

```
Features.trans.xxx{
xxxx
}
```
这些块可以理解成是各个插件的构成？
希望博主能在空闲时候帮忙解疑答惑，拜谢！

**Comment by ahuai** [comment]
`greet + 👋 + version+  author + execute format <configuration> + mention /lang + /op_lang + /trans + /dict + /learn.  If it is in gpt plugin mode metion /plugins.`
这段描述也没懂。

**Comment by ZhangHanDong** [comment]
@ahuai 建议你先找 吴恩达的 prompt 课程学习一下就懂了。
