### ISSUE TITLE
chatgpt 3.5

### ISSUE THREAD

**Issue by Zarahhhhhh** [Illumine-Labs/Mr.Translate#3]
您好，我想问一下，如果使用的是3.5版本，这个prompt是直接以对话的形式发送来设定吗？可是他给的回复是“看来您已经为具有各种命令和功能的人工智能语言翻译器提供了详细的脚本和配置。如果您有任何具体问题，或者您想在此脚本中讨论或修改某些具体内容，请告诉我，我很乐意为您提供帮助！”，请问那这个样子的话，是我操作失误了吗？非常感谢，希望能够得到回复~

**Comment by ZhangHanDong** [comment]
成功与否你直接问gpt即可。
